INDEX_CONSTITUENTS_COUNT = 100
INSTRUMENTS_TO_FETCH = 120
LOOKBACK_DAYS_FOR_UI = 30
DATA_STORE_PERIOD = "1mo"
YFINANCE_DEFAULT_LOOKBACK_PERIOD = "1y"
NASDAQ_API_URL = "https://api.nasdaq.com/api/screener/stocks"
